import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import RecoilRootProvider from '../utils/RecoilRootProvider'
import ReactQueryProviders from '@/utils/ReactQueryProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProviders>
          <RecoilRootProvider>
            {children}
            </RecoilRootProvider>
        </ReactQueryProviders>
        </body>
    </html>
  )
}
